// Shared types across client and server.

export type RouteName = "全球加速";
export type Billing = "特价" | "官方";
export type Resolution = "512" | "1K" | "2K" | "4K";
export type ModelName = "Nano Banana Pro" | "Nano Banana 2" | "Nano Banana" | "GPT Image 2";
/** Only meaningful for GPT Image 2 — the nano-banana family has no quality knob. */
export type Quality = "auto" | "high" | "medium" | "low";

export interface SettingsDefaults {
  model: ModelName;
  resolution: Resolution;
  billing: Billing;
  aspectRatio: string;
}

export interface Settings {
  apiKey: string;
  route: RouteName;
  defaults: SettingsDefaults;
}

export type PublicSettings = Omit<Settings, "apiKey"> & {
  hasApiKey: boolean;
  apiKeyMasked: string;
};

// new-api 账户额度是整数计数，$1 = 500000 单位；登录/UserChip 都按这个常量换算显示。
export const QUOTA_PER_UNIT = 500000;

/** Trimmed new-api 用户对象，登录/me 接口透传给前端的唯一形状（不含 role/group 等敏感字段）。 */
export interface AuthUser {
  id: number | string;
  username: string;
  display_name?: string;
  quota?: number;
}

export type JobStatus = "running" | "success" | "failed";

export interface JobStatusResponse {
  id: string;
  status: JobStatus;
  progress: number | null;
  images: string[]; // local media URLs
  error?: string;
}

export interface GenMeta {
  prompt: string;
  model: ModelName;
  resolution: Resolution;
  aspectRatio: string;
  billing: Billing;
  count: number;
  createdAt: number;
  /** Number of free-form reference images attached at submit time (multi-ref
   *  feature). Optional: history entries written before this field existed
   *  won't have it. Record-only — HistoryPage.tsx's pick() lists GenParams
   *  fields explicitly, so this never leaks into updateParams/GenParams. */
  refCount?: number;
  /** GPT Image 2 only. Optional: history entries written before this field
   *  existed, or generated with a different model, won't have it. */
  quality?: Quality;
  /** Batch workshop (PLAN-BATCH) only: a short "服装文件名 · 模特N" label for
   *  this particular cell's combination, so a history entry generated by the
   *  workshop can still be told apart from a regular single-image one at a
   *  glance. Record-only — HistoryPage.tsx's pick() lists GenParams fields
   *  explicitly, so this never leaks into updateParams/GenParams. */
  note?: string;
  /** Task-mode provenance. Optional so older history entries and regular
   *  single/batch generations keep the same shape. */
  workflowId?: string;
  workflowRunId?: string;
  workflowNodeId?: string;
}

export interface HistoryItem {
  name: string;
  url: string;
  createdAt: number;
  size: number;
  meta?: GenMeta;
  /** 视频任务元信息（视频历史条目专用，与 meta 互斥）。 */
  videoMeta?: VideoMeta;
}

/** 视频生成任务的参数快照（写入 data/video-meta.json sidecar）。 */
export interface VideoMeta {
  taskId:   string;
  model:    string;
  mode:     string;
  duration: number;
  prompt:   string;
  negativePrompt?: string;
  shots:    { index: number; prompt: string; duration: number }[];
  sound:    boolean;
  watermark?: boolean;
  webSearch?: boolean;
  aspectRatio: string;
  frameMode?: "refs" | "frames";
  createdAt: number;
}

export interface GenParams {
  prompt: string;
  model: ModelName;
  resolution: Resolution;
  aspectRatio: string;
  billing: Billing;
  count: number;
  /** GPT Image 2 only; ignored by the nano-banana family's submit body. */
  quality: Quality;
}

/** Natural-pixel rect (padded, clamped) a local-repaint crop/composite operates on. */
export interface InpaintBBox {
  x: number;
  y: number;
  w: number;
  h: number;
}

/** Live brush selection: a feathered alpha-mask PNG (natural image size) + its bounding box. */
export interface InpaintMask {
  maskUrl: string;
  bboxPx: InpaintBBox;
}

/** Snapshot of the mask/bbox/source image taken at submit time, so a later mask edit
 *  (e.g. the user reopens the brush panel while a job is still running) can't affect
 *  how an in-flight job's results get composited back. */
export interface InpaintJob {
  origSrc: string;
  bboxPx: InpaintBBox;
  maskUrl: string;
}
